services:
  bank:
    build:
      context: ./java/bank
      dockerfile: Dockerfile
    container_name: bank
    restart: always
    environment:
      MARIADB_URL: jdbc:mariadb://bank-db:3306/bank
      MARIADB_USER: user
      MARIADB_PASSWORD: 1

      REDIS_HOST: bank-redis

      MINIO_URL: http://bank-minio:9000
      MINIO_USER: admin
      MINIO_PASSWORD: 12345678

      SERVER_SHOP_URL: http://shop-nginx
    depends_on:
      bank-db:
        condition: service_healthy
      bank-redis:
        condition: service_started
      bank-minio:
        condition: service_started

  bank-php-gateway:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: bank-php-gateway
    restart: always
    environment:
      JAVA_HOST: bank
      REDIS_HOST: bank-redis
    depends_on:
      bank:
        condition: service_started
      bank-redis:
        condition: service_started

  bank-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: bank-nginx
    restart: always
    depends_on:
      bank-php-gateway:
        condition: service_started

  bank-minio:
    image: minio/minio
    container_name: bank-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bank_minio_data:/data
    command: server /data --console-address ":9001"

  bank-redis:
    image: redis
    container_name: bank-redis
    command: redis-server
    volumes:
      - bank_redis_data:/data

  bank-db:
    image: mariadb
    container_name: bank-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1
      MARIADB_DATABASE: bank
      MARIADB_USER: user
      MARIADB_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - bank_db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  bank_db_data:
  bank_minio_data:
  bank_redis_data: