services:
  bank:
    build:
      context: ./java/bank
      dockerfile: Dockerfile
    container_name: bank
    restart: always
    env_file:
      - .env
    depends_on:
      - bank-db
      - bank-redis
      - bank-minio

  bank-php-gateway:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: bank-php-gateway
    restart: always
    environment:
      JAVA_HOST: bank
      REDIS_HOST: bank-redis
    depends_on:
      - bank
      - bank-redis

  bank-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: bank-nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      bank-php-gateway:
        condition: service_healthy

  bank-minio:
    image: minio/minio
    container_name: bank-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - bank_minio_data:/data
    command: server /data --console-address ":9001"

  bank-redis:
    image: redis
    container_name: bank-redis
    command: redis-server
    volumes:
      - bank_redis_data:/data

  bank-db:
    image: mariadb
    container_name: bank-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1
      MARIADB_DATABASE: bank
      MARIADB_USER: user
      MARIADB_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - bank_db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  bank_db_data:
  bank_minio_data:
  bank_redis_data:
