server {
    listen 8080;
    root /var/www/payment;
    location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9001;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
    }
}